version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: example-web
    hostname: example-web
    ports:
      - "8081:80"
    expose:
      - "80"
    networks:
      app_net:
        aliases:
          - example.local
    restart: unless-stopped

  test-client:
    image: alpine:latest
    container_name: test-client
    command: tail -f /dev/null
    networks:
      - app_net
    depends_on:
      - web
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
    name: my_custom_network
