version: '3.8'

services:
  local-dns:
    build: .
    container_name: hyper-dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      hypernet:
        aliases:
          - dns
    restart: unless-stopped

  # Example service - customize as needed
  server:
    image: nginx:alpine
    container_name: example-server
    networks:
      hypernet:
    dns:
      - local-dns
    restart: unless-stopped

  # Add more services as needed

networks:
  hypernet:
    driver: bridge
    name: hypermodular_net
