version: '3.8'

services:
  dns:
    image: coredns/coredns:latest
    container_name: hyper-dns
    hostname: dns
    command: -conf /etc/coredns/Corefile
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ./coredns:/etc/coredns
    networks:
      hypernet:
        ipv4_address: 172.30.0.2
    restart: unless-stopped

  # Example web service
  web:
    image: nginx:alpine
    container_name: example-web
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=example.local
    networks:
      hypernet:
    dns: 172.20.0.2
    depends_on:
      - dns
    restart: unless-stopped

networks:
  hypernet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
