version: '3.8'

services:
  dns:
    image: jpillora/dnsmasq:latest
    container_name: hyper-dns
    hostname: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    networks:
      hypernet:
        ipv4_address: 172.30.0.2
    restart: unless-stopped

  # Example web service
  web:
    image: nginx:alpine
    container_name: example-web
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=example.local
    networks:
      hypernet:
    dns: 172.20.0.2
    depends_on:
      - dns
    restart: unless-stopped

networks:
  hypernet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
